apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: aaserver-default
spec:
  ## Used by services inside the Kubernetes cluster
  destination:
    name: aaserver-service
  precedence: 1
  route:
  - labels:
      version: v1
